spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:marketplace}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:marketplace-local-password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.flyway.enabled=true
