spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/pgnaver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:marketplace}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:marketplace-local-password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none


