spring.application.name=settlement-service
server.port=8083
spring.profiles.default=local
spring.docker.compose.enabled=false
spring.flyway.default-schema=marketplace
spring.flyway.create-schemas=true
