spring.datasource.url=jdbc:h2:mem:settlement-local;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
server.address=127.0.0.1
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
